/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Report API and database availability. Public endpoint (no auth).
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and start a session (httpOnly cookie).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the session by clearing the cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently authenticated user.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wallets */
        get: operations["list_wallets_api_v1_wallets_get"];
        put?: never;
        /** Create Wallet */
        post: operations["create_wallet_api_v1_wallets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wallet Totals
         * @description Combined balance per currency across the user's wallets.
         */
        get: operations["get_wallet_totals_api_v1_wallets_totals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{wallet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wallet */
        get: operations["get_wallet_api_v1_wallets__wallet_id__get"];
        put?: never;
        post?: never;
        /** Delete Wallet */
        delete: operations["delete_wallet_api_v1_wallets__wallet_id__delete"];
        options?: never;
        head?: never;
        /** Update Wallet */
        patch: operations["update_wallet_api_v1_wallets__wallet_id__patch"];
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List user's categories and system defaults.
         */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category Endpoint */
        get: operations["get_category_endpoint_api_v1_categories__category_id__get"];
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description List transactions for the user's wallets, newest first. Hidden ones only on request.
         */
        get: operations["list_transactions_api_v1_transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/uncategorized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Uncategorized
         * @description The review inbox: transactions still waiting for a category, newest first.
         */
        get: operations["list_uncategorized_api_v1_transactions_uncategorized_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Transactions
         * @description Apply the same changes to several transactions: all of them or, if any is refused, none.
         */
        post: operations["bulk_update_transactions_api_v1_transactions_bulk_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Delete Transactions
         * @description Delete several transactions entered by hand; refused (409) if any came from a bank.
         */
        post: operations["bulk_delete_transactions_api_v1_transactions_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_v1_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_v1_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_api_v1_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}/categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Categorize
         * @description Set the category; with apply_to_similar, also for the merchant's other and future transactions.
         */
        post: operations["categorize_api_v1_transactions__transaction_id__categorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Statistics
         * @description Get overall statistics for the current user.
         */
        get: operations["get_statistics_api_v1_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Get a financial report for a specific period.
         */
        get: operations["get_report_api_v1_statistics_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank/aspsps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Banks
         * @description Banks available for connection in a country.
         */
        get: operations["list_banks_api_v1_bank_aspsps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_v1_bank_connections_get"];
        put?: never;
        /**
         * Start Connection
         * @description Start connecting a bank; the client then sends the user to the returned URL.
         */
        post: operations["start_connection_api_v1_bank_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank/connections/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Connection
         * @description Finish the connection with the code and state the bank sent back.
         */
        post: operations["complete_connection_api_v1_bank_connections_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Connection
         * @description Disconnect a bank. Wallets and imported transactions are kept.
         */
        delete: operations["delete_connection_api_v1_bank_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank/accounts/{account_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Account
         * @description Link a bank account to a wallet (or to a new wallet when wallet_id is null).
         */
        post: operations["link_account_api_v1_bank_accounts__account_id__link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Import new transactions from every linked bank account.
         */
        post: operations["sync_api_v1_bank_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rules
         * @description The user's merchant rules, by merchant.
         */
        get: operations["list_rules_api_v1_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Rule
         * @description Forget a rule. Transactions keep their categories.
         */
        delete: operations["delete_rule_api_v1_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Merchants
         * @description The user's merchants that have transactions, by name.
         */
        get: operations["list_user_merchants_api_v1_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AspspRead
         * @description A bank (ASPSP = Account Servicing Payment Service Provider) available for connection.
         */
        AspspRead: {
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Logo */
            logo?: string | null;
        };
        /** BankAccountRead */
        BankAccountRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Iban Last4 */
            iban_last4: string | null;
            /** Wallet Id */
            wallet_id: number | null;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /** BankConnectionRead */
        BankConnectionRead: {
            /** Id */
            id: number;
            /** Aspsp Name */
            aspsp_name: string;
            /** Aspsp Country */
            aspsp_country: string;
            status: components["schemas"]["ConnectionStatus"];
            /** Valid Until */
            valid_until: string | null;
            /** Accounts */
            accounts: components["schemas"]["BankAccountRead"][];
        };
        /** BulkResult */
        BulkResult: {
            /** Affected */
            affected: number;
        };
        /**
         * BulkTransactionChanges
         * @description Changes for every selected transaction. A field left out means "no change".
         */
        BulkTransactionChanges: {
            /** Category Id */
            category_id?: number | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Description */
            description?: string | null;
            /** Is Hidden */
            is_hidden?: boolean | null;
            /** Merchant Name */
            merchant_name?: string | null;
        };
        /** BulkTransactionDelete */
        BulkTransactionDelete: {
            /** Transaction Ids */
            transaction_ids: number[];
        };
        /** BulkTransactionUpdate */
        BulkTransactionUpdate: {
            /** Transaction Ids */
            transaction_ids: number[];
            changes: components["schemas"]["BulkTransactionChanges"];
        };
        /** CategorizeRequest */
        CategorizeRequest: {
            /** Category Id */
            category_id: number;
            /**
             * Apply To Similar
             * @default false
             */
            apply_to_similar: boolean;
        };
        /** CategorizeResultRead */
        CategorizeResultRead: {
            transaction: components["schemas"]["TransactionRead"];
            rule: components["schemas"]["MerchantRuleRead"] | null;
            /** Similar Updated */
            similar_updated: number;
        };
        /**
         * CategoryBreakdown
         * @description Category breakdown for a report.
         */
        CategoryBreakdown: {
            /** Category Id */
            category_id: number;
            /** Category Name */
            category_name: string;
            type: components["schemas"]["CategoryType"];
            /** Total */
            total: string;
            /** Count */
            count: number;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["CategoryType"];
            /** Parent Id */
            parent_id?: number | null;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["CategoryType"];
            /** Parent Id */
            parent_id: number | null;
            /** Key */
            key: string | null;
            /** Is Group */
            is_group: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CategorySource
         * @description Who chose a transaction's category. Automatic choices never override the user's.
         * @enum {string}
         */
        CategorySource: "manual" | "rule" | "mcc" | "default";
        /**
         * CategoryTotal
         * @description Total amount for a single category.
         */
        CategoryTotal: {
            /** Category Id */
            category_id: number;
            /** Category Name */
            category_name: string;
            /** Total */
            total: string;
        };
        /**
         * CategoryType
         * @enum {string}
         */
        CategoryType: "income" | "expense" | "transfer";
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: number | null;
        };
        /** ConnectionComplete */
        ConnectionComplete: {
            /** State */
            state: string;
            /** Code */
            code: string;
        };
        /** ConnectionStart */
        ConnectionStart: {
            /** Aspsp Name */
            aspsp_name: string;
            /** Country */
            country: string;
        };
        /** ConnectionStartResponse */
        ConnectionStartResponse: {
            /** Url */
            url: string;
        };
        /**
         * ConnectionStatus
         * @enum {string}
         */
        ConnectionStatus: "pending" | "active" | "expired";
        /**
         * CurrencyTotal
         * @description Combined balance of all wallets in one currency. Currencies are never mixed.
         */
        CurrencyTotal: {
            /** Currency */
            currency: string;
            /** Balance */
            balance: string;
            /** Wallet Count */
            wallet_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Availability of the API and its dependencies.
         */
        HealthResponse: {
            api: components["schemas"]["ServiceStatus"];
            database: components["schemas"]["ServiceStatus"];
        };
        /** LinkAccountRequest */
        LinkAccountRequest: {
            /** Wallet Id */
            wallet_id?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MerchantRead */
        MerchantRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** MerchantRuleRead */
        MerchantRuleRead: {
            /** Id */
            id: number;
            /** Merchant Name */
            merchant_name: string;
            /** Category Id */
            category_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReportPeriod
         * @description Time period for a report.
         */
        ReportPeriod: {
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
        };
        /**
         * ReportResponse
         * @description Period-based financial report.
         */
        ReportResponse: {
            period: components["schemas"]["ReportPeriod"];
            summary: components["schemas"]["ReportSummary"];
            /** By Category */
            by_category: components["schemas"]["CategoryBreakdown"][];
            /** By Wallet */
            by_wallet: components["schemas"]["WalletBreakdown"][];
        };
        /**
         * ReportSummary
         * @description Summary statistics for a report period.
         */
        ReportSummary: {
            /** Income */
            income: string;
            /** Expenses */
            expenses: string;
            /** Net Change */
            net_change: string;
            /** Transaction Count */
            transaction_count: number;
        };
        /**
         * ServiceStatus
         * @description Availability of a single service component.
         * @enum {string}
         */
        ServiceStatus: "ok" | "down";
        /**
         * StatisticsResponse
         * @description Overall statistics for a user.
         */
        StatisticsResponse: {
            /** Total Balance */
            total_balance: string;
            /** Total Income */
            total_income: string;
            /** Total Expenses */
            total_expenses: string;
            /** Wallet Balances */
            wallet_balances: components["schemas"]["WalletBalance"][];
            /** Spending By Category */
            spending_by_category: components["schemas"]["CategoryTotal"][];
            /** Income By Category */
            income_by_category: components["schemas"]["CategoryTotal"][];
        };
        /** SyncResultRead */
        SyncResultRead: {
            /** Bank Account Id */
            bank_account_id: number;
            /** Imported */
            imported: number;
            /** Categorized */
            categorized: number;
            /** Error */
            error: string | null;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Wallet Id */
            wallet_id: number;
            /** Category Id */
            category_id: number;
            /** Amount */
            amount: number | string;
            /** Description */
            description?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** TransactionPage */
        TransactionPage: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["TransactionRead"][];
        };
        /** TransactionRead */
        TransactionRead: {
            /** Id */
            id: number;
            /** Wallet Id */
            wallet_id: number;
            /** Category Id */
            category_id: number;
            category_source: components["schemas"]["CategorySource"];
            /** Amount */
            amount: string;
            /** Description */
            description: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Counterparty */
            counterparty: string | null;
            /** Merchant Category Code */
            merchant_category_code: string | null;
            /** Merchant Key */
            merchant_key: string | null;
            merchant: components["schemas"]["MerchantRead"] | null;
            /** Is Imported */
            is_imported: boolean;
            /** Is Hidden */
            is_hidden: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Category Id */
            category_id?: number | null;
            /** Amount */
            amount?: number | string | null;
            /** Description */
            description?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /**
             * Is Hidden
             * @default false
             */
            is_hidden: boolean;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WalletBalance
         * @description Balance information for a single wallet.
         */
        WalletBalance: {
            /** Wallet Id */
            wallet_id: number;
            /** Wallet Name */
            wallet_name: string;
            /** Balance */
            balance: string;
        };
        /**
         * WalletBreakdown
         * @description Wallet breakdown for a report.
         */
        WalletBreakdown: {
            /** Wallet Id */
            wallet_id: number;
            /** Wallet Name */
            wallet_name: string;
            /** Income */
            income: string;
            /** Expenses */
            expenses: string;
            /** Net Change */
            net_change: string;
        };
        /** WalletCreate */
        WalletCreate: {
            /** Name */
            name: string;
            /** @default bank */
            type: components["schemas"]["WalletType"];
            /**
             * Currency
             * @description ISO 4217 currency code, e.g. EUR
             * @default EUR
             */
            currency: string;
            /**
             * Initial Balance
             * @default 0
             */
            initial_balance: number | string;
        };
        /** WalletRead */
        WalletRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["WalletType"];
            /** Currency */
            currency: string;
            /** Initial Balance */
            initial_balance: string;
            /** Balance */
            balance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * WalletType
         * @enum {string}
         */
        WalletType: "bank" | "cash" | "digital" | "stash";
        /** WalletUpdate */
        WalletUpdate: {
            /** Name */
            name?: string | null;
            type?: components["schemas"]["WalletType"] | null;
            /** Currency */
            currency?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_wallets_api_v1_wallets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletRead"][];
                };
            };
        };
    };
    create_wallet_api_v1_wallets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wallet_totals_api_v1_wallets_totals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyTotal"][];
                };
            };
        };
    };
    get_wallet_api_v1_wallets__wallet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wallet_api_v1_wallets__wallet_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_wallet_api_v1_wallets__wallet_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_endpoint_api_v1_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_v1_transactions_get: {
        parameters: {
            query?: {
                wallet_id?: number | null;
                include_hidden?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_uncategorized_api_v1_transactions_uncategorized_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_transactions_api_v1_transactions_bulk_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_transactions_api_v1_transactions_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTransactionDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_v1_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_v1_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_v1_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categorize_api_v1_transactions__transaction_id__categorize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategorizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizeResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_statistics_api_v1_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsResponse"];
                };
            };
        };
    };
    get_report_api_v1_statistics_report_get: {
        parameters: {
            query: {
                /** @description Start date for the report period */
                start_date: string;
                /** @description End date for the report period */
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_banks_api_v1_bank_aspsps_get: {
        parameters: {
            query: {
                country: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AspspRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_api_v1_bank_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankConnectionRead"][];
                };
            };
        };
    };
    start_connection_api_v1_bank_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_connection_api_v1_bank_connections_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionComplete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankConnectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_api_v1_bank_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_account_api_v1_bank_accounts__account_id__link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankAccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_v1_bank_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultRead"][];
                };
            };
        };
    };
    list_rules_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantRuleRead"][];
                };
            };
        };
    };
    delete_rule_api_v1_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_merchants_api_v1_merchants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantRead"][];
                };
            };
        };
    };
}
